### ISSUE TITLE
Hover Animation

### ISSUE THREAD

**Issue by Bhavya1403** [csivitu/vbay#11]
Describe the solution you'd like
Add a feature to get hover animation for 0.5 second with ease in transition to the buy now button present below the product images on products page.

**Comment by alvinokafor** [comment]
Hi Bhavya, i would love to work on this issue

**Comment by SubstantialCattle5** [comment]
Please tag moderators 
something similar to  @alvinokafor

**Comment by gaurav-iitb** [comment]
hi @Bhavya1403 I would like to work on this. please assign this to me

**Comment by gaurav-iitb** [comment]
buy now button is not visible to me in the products page

**Comment by alvinokafor** [comment]
> buy now button is not visible to me in the products page

the class selector wasn't added to the html tag, i've fixed that too

**Comment by codeboyfriend** [comment]
.buy-btn:hover{
 css style
}

That's the simple way to fix this. You can assign it to me nd see how wonderful it'll be

**Comment by codeboyfriend** [comment]
Thanks for assigning this to me.. I'll give it my all to meet your satisfaction
