### ISSUE TITLE
Scroll bar customization

### ISSUE THREAD

**Issue by Bhavya1403** [csivitu/vbay#13]
Is your feature request related to a problem? Please describe.
Adding a scroll bar which is unique to a website shows attention to detail.

Describe the solution you'd like
Customize scroll bar on all pages with the following specifications: [ width= 15 px, border radius= 10px, color of bar= black]

**Comment by laxmanbalaraman** [comment]
Hey, I would like to work on this issue, can you assign me? :)

**Comment by SubstantialCattle5** [comment]
Hey please tag our  moderators . 
ex-  @laxmanbalaraman

**Comment by laxmanbalaraman** [comment]
@Bhavya1403 @SubstantialCattle5 @3xpl0itk1t  I have completed the scroll bar customization and created a pr. Kindly review them. Thanks :)

**Comment by laxmanbalaraman** [comment]
Hey @Bhavya1403 ! I have created a PR and its ready to be merged #31 and so no conflicts now. Please Review it. :)
