### ISSUE TITLE
Missing Reviews 

### ISSUE THREAD

**Issue by Bhavya1403** [csivitu/vbay#14]
Describe the bug
The review page is empty with no place for reviews.

To Reproduce
1. Go to review.html
3. See error

Expected behavior
Add an image field and a text field with a button to post reviews on the review page.

Screenshots
![image](https://user-images.githubusercontent.com/103041874/193343865-16613455-d9c4-445d-b2db-c4623e58748b.png)

**Comment by Vaani-pathariya** [comment]
Can I contribute to this one ?

**Comment by gautam-mh** [comment]
assign me this issue
