### ISSUE TITLE
Light theme and dark theme

### ISSUE THREAD

**Issue by Bhavya1403** [csivitu/vbay#18]
Is your feature request related to a problem? Please describe.
My eyes always hurt when I use the light mode for too long.

Describe the solution you'd like
Add light theme and dark theme with a button to switch between the two on the home page.

**Comment by ozirichigozie** [comment]
# Hello @Bhavya1403 👋

Light mode also hurts my eyes 👀 a lot. I would like to proffer a solution to the problem using JavaScript.

Thank you.

**Comment by gaurav-iitb** [comment]
Hi , Same happens with me I wish to add this feature in some project it is great to find this issue. I Would love to work on this please assign this to me
