### ISSUE TITLE
 Background Correction

### ISSUE THREAD

**Issue by Bhavya1403** [csivitu/vbay#3]
Describe the bug
The background does not fit properly on all the pages and it is missing on some of the pages.

To Reproduce
1. Go to index.html
2. Navigate to the different pages by clicking on the page buttons in the navbar present on the top right corner of the index page.
3. See error

Expected behavior
Add/edit code with the same background image(bg.jpg) on all the pages so that it fits perfectly.

**Comment by gautam-mh** [comment]
assign me this issue

**Comment by ChaudharyRaman** [comment]
Hi @Bhavya1403 . I would like to contribute to this issue . can you assign it to me?

**Comment by Ashwin-hp** [comment]
@Bhavya1403 please assign this issue to me

**Comment by acashgirii** [comment]
@Bhavya1403 kindly assign this issue to me!
