### ISSUE TITLE
Carousel needed

### ISSUE THREAD

**Issue by Bhavya1403** [csivitu/vbay#37]
Is your feature request related to a problem? Please describe.
It’s always nice to have a featured product list while surfing on ecommerce sites

Describe the solution you'd like
Add a carousel for featured products on the bottom of the home page with minimum 3 products of your choice.

**Comment by aryan16x** [comment]
Assign this to me

**Comment by ChaudharyRaman** [comment]
Hi @Bhavya1403 . I have created a PR for Carousel please check and Merge if it Satisfies your requirement.

**Comment by sanjaybaskaran01** [comment]
#74  Merged
