### ISSUE TITLE
Structure files

### ISSUE THREAD

**Issue by Bhavya1403** [csivitu/vbay#4]
Describe the bug
The project files are not properly arranged.

To Reproduce
1. Go to vbay repo
2. See error

Expected behavior
Separate all the html and css files into different folders.

**Comment by neutr0n420** [comment]
Hey, Can I would like to work on this issue can you assign this issue to me?

**Comment by pratiksrivastava01** [comment]
@Bhavya1403  can i also work on this

**Comment by GOPINISAIBHUVAN** [comment]
CAN YOU ASSIGN THIS TO ME
