### ISSUE TITLE
Quantity dropdown

### ISSUE THREAD

**Issue by Bhavya1403** [csivitu/vbay#40]
Is your feature request related to a problem? Please describe.
There is no quantity menu dropdown provided .

Describe the solution you'd like
Add a dropdown menu named Quantity with values ranging from 1 to 5 next to the price written on the products page.

**Comment by RahulSankhla312** [comment]
hey @Bhavya1403  could you assign this issue to me ?

**Comment by Bhavya1403** [comment]
You can start working on the issues without requesting to be assigned.
