### ISSUE TITLE
Centre the content

### ISSUE THREAD

**Issue by Bhavya1403** [csivitu/vbay#5]
Describe the bug
The written content along with the image is not centrally placed on the index.html page

To Reproduce
1. Go to index.html
2. Scroll down to see the content with the image.
3. See error

Expected behavior
Align content so that it is placed at the center of the page

Screenshots
![image](https://user-images.githubusercontent.com/103041874/193341339-50d95d21-562a-442d-a7ed-ca094036b444.png)

**Comment by ChaudharyRaman** [comment]
Hi @Bhavya1403. I would like to work on this issue. can you assign it to me?

**Comment by DhruvTrehan39** [comment]
Hi @Bhavya1403. The photos are not loaded, Is this the final preview.

**Comment by gautam-mh** [comment]
assign me this issue
