### ISSUE TITLE
Shorten Nav Bar

### ISSUE THREAD

**Issue by Bhavya1403** [csivitu/vbay#6]
Is your feature request related to a problem? Please describe.
I always prefer a hamburger menu for my nav bar when I am surfing any ecommerce site on my phone.

Describe the solution you'd like
Shorten nav bar(home, products, cart, review present on top right corner) to a hamburger menu for mobile view.

**Comment by mehraankush** [comment]
hey i would love to contribute ..

**Comment by Ashwin-hp** [comment]
Pls assign this issue to me

**Comment by Bhavya1403** [comment]
@Ashwin-hp @Ashwin-hp Anyone can solve this issue without requesting to be assigned! Therefore start solving :)
