### ISSUE TITLE
Arrange cart page

### ISSUE THREAD

**Issue by Bhavya1403** [csivitu/vbay#65]
Describe the bug
The cart items on the cart page are randomly placed.

To Reproduce
1. Go to cart.html
2. See error

Expected behavior
Align the content on the cart page. Segregate different sections of the cart with lines.

Screenshots
![image](https://user-images.githubusercontent.com/103041874/193435739-8e2c3d71-5920-47e2-aadf-3e5134c50c3c.png)

**Comment by laxmanbalaraman** [comment]
I would like to work on this one. can you assign me @Bhavya1403 .
