### ISSUE TITLE
Thank you page

### ISSUE THREAD

**Issue by Bhavya1403** [csivitu/vbay#66]
Is your feature request related to a problem? Please describe.
The thank you for shopping with us page always makes me smile :)

Describe the solution you'd like
After issue #17 has been solved, click on the confirm payment button. After confirm payment is clicked, a loading animation should appear and then after 3 seconds, a page saying “Payment Successful! Thank you for shopping with us!” should be seen.

**Comment by Mustafa-Azad025** [comment]
hey @Bhavya1403 ,
You Want it as a popup or as a page

**Comment by Bhavya1403** [comment]
@Mustafa-Azad025 The loading animation should be a pop up but the thank you for shopping with us should be a page.

**Comment by Mustafa-Azad025** [comment]
Will you assign this to me .

**Comment by Bhavya1403** [comment]
you can work on this issue without being assigned to it
