### ISSUE TITLE
Add to cart functionality

### ISSUE THREAD

**Issue by Bhavya1403** [csivitu/vbay#67]
Describe the bug
The cart page is static and is not updated when buy now is clicked on the products page.

To Reproduce
1. Go to products.html
2. Click on buy now
3. Go to cart.html

Expected behavior
When buy now is clicked on the products page, the product selected with the quantity should be updated on the cart page.

**Comment by droffilc1** [comment]
Hello @Bhavya1403 I would like to contribute to this issue..

**Comment by JatinSingh08** [comment]
Hey @Bhavya1403 Please assign this to me.

**Comment by Bhavya1403** [comment]
@JatinSingh08 @droffilc1  you can start working on this without being assigned to it
