### ISSUE TITLE
Redirect to Home Page

### ISSUE THREAD

**Issue by Bhavya1403** [csivitu/vbay#7]
Is your feature request related to a problem? Please describe.
It’s always nice when clicking on the logo redirects to the home page.

Describe the solution you'd like
Add feature so that when one clicks on the VBAY logo present on top left of all pages, it should redirect to home page.

**Comment by samay-v** [comment]
@Bhavya1403 I'd like to work on this :D

**Comment by pratiksrivastava01** [comment]
@Bhavya1403  The feature on the website so that when the VIBAY logo is present on the top left corner can be fixed by adding an anchor tag that is assigned with the value of the index.html file and then placing the image inside it.

`<a href="index.html">

					<img src="logo.png" width="150px" />
				</a>`

**Comment by 3xpl0itk1t** [comment]
> @Bhavya1403 The feature on the website so that when the VIBAY logo is present on the top left corner can be fixed by adding an anchor tag that is assigned with the value of the index.html file and then placing the image inside it.
> 
> ```
> <a href="index.html">
> 
> 					<img src="logo.png" width="150px" />
> 				</a>
> ```

You have to make changes in the source code and make a pr don't put your solutions in comments
