### ISSUE TITLE
Malfunctioning scroll bar

### ISSUE THREAD

**Issue by Bhavya1403** [csivitu/vbay#8]
Describe the bug
The products page does not scroll in the y axis.

To Reproduce
1. Go to products page'
2. Check the scroll bar which only scrolls in the x axis
3. See error

Expected behavior
Enable the scroll bar in the y axis

**Comment by gautam-mh** [comment]
assign me this issue

**Comment by ChaudharyRaman** [comment]
Hii @Bhavya1403 . I would like to work on this issue. can you please assign it to me?

**Comment by TanishqSrivastava** [comment]
Can I work on this issue?
